package com.carsonlius.boot.model;

import java.util.Date;

public class SystemLogDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log_details.rec_id
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    private Integer recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log_details.remark
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log_details.request_id
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    private String requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log_details.created_at
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log_details.updated_at
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log_details.data
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log_details.rec_id
     *
     * @return the value of system_log_details.rec_id
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log_details.rec_id
     *
     * @param recId the value for system_log_details.rec_id
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log_details.remark
     *
     * @return the value of system_log_details.remark
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log_details.remark
     *
     * @param remark the value for system_log_details.remark
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log_details.request_id
     *
     * @return the value of system_log_details.request_id
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log_details.request_id
     *
     * @param requestId the value for system_log_details.request_id
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log_details.created_at
     *
     * @return the value of system_log_details.created_at
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log_details.created_at
     *
     * @param createdAt the value for system_log_details.created_at
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log_details.updated_at
     *
     * @return the value of system_log_details.updated_at
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log_details.updated_at
     *
     * @param updatedAt the value for system_log_details.updated_at
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log_details.data
     *
     * @return the value of system_log_details.data
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log_details.data
     *
     * @param data the value for system_log_details.data
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    public void setData(String data) {
        this.data = data;
    }
}