package com.carsonlius.boot.mapper;

import com.carsonlius.boot.model.SystemLogDetails;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SystemLogDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    int insert(SystemLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    int insertSelective(SystemLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    SystemLogDetails selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    int updateByPrimaryKeySelective(SystemLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SystemLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log_details
     *
     * @mbg.generated Wed Nov 04 18:50:42 CST 2020
     */
    int updateByPrimaryKey(SystemLogDetails record);
}